import type { Locale } from "@/lib/i18n";

export type LegalDocument = { title: string; summary: string; sections: Array<{ title: string; paragraphs: string[] }> };

export const LEGAL_VERSION = "1.0";
export const LEGAL_UPDATED_AT = "2026-08-24";

const common = {
  ru: { effective: "Редакция от 24 августа 2026 года.", operator: "Оператор сайта и сопровождающий проекта: владелец репозитория job_ftch (GitHub: letya999). Запросы направляются через контакт владельца, указанный в репозитории. Не передавайте персональные данные в публичных GitHub issues." },
  en: { effective: "Effective 24 August 2026.", operator: "Website operator and project maintainer: the owner of the job_ftch repository (GitHub: letya999). Send requests through the maintainer contact listed in the repository. Do not place personal data in public GitHub issues." },
};

export const legalDocuments: Record<Locale, Record<string, LegalDocument>> = {
  ru: {
    privacy: { title: "Политика обработки персональных данных", summary: "Какие данные может обрабатывать сайт, зачем, на каком основании и как реализовать права субъекта.", sections: [
      { title: "1. Оператор и область действия", paragraphs: [common.ru.effective, common.ru.operator, "Политика применяется к публичному сайту job_ftch, его read-only API и связанным страницам документации. Она не регулирует обработку данных сторонними сайтами вакансий и Telegram."] },
      { title: "2. Категории данных", paragraphs: ["Регистрация и профиль пользователя отсутствуют. Сайт может обрабатывать IP-адрес и технические журналы безопасности на стороне инфраструктуры; URL, referrer, тип браузера, устройства и обезличенные события — только при включённой аналитике и после согласия; выбор языка, темы и consent — локально в браузере.", "Сайт не запрашивает паспортные, платёжные, медицинские, биометрические или иные специальные категории данных. Не отправляйте такие данные через публичные каналы проекта."] },
      { title: "3. Цели и основания", paragraphs: ["Технические журналы используются для доставки сайта, предотвращения злоупотреблений, диагностики и защиты API на основании необходимости эксплуатации и законного интереса в безопасности. Аналитика используется только на основании явного согласия для оценки посещаемости и качества интерфейса.", "Согласие можно не давать или отозвать без ограничения доступа к основным функциям."] },
      { title: "4. Получатели и трансграничная передача", paragraphs: ["При включении соответствующих production-настроек данные аналитики могут передаваться Google Analytics и Yandex Metrika по их условиям. До согласия их скрипты не загружаются. Хостинг и сетевые провайдеры могут обрабатывать технические журналы как обработчики данных.", "Применимость трансграничной передачи зависит от выбранного владельцем хостинга и включённых счётчиков. Оператор обязан проверить локализацию и договорные основания до production-запуска аналитики."] },
      { title: "5. Сроки, удаление и безопасность", paragraphs: ["Consent и настройки хранятся в localStorage до очистки браузера или изменения выбора. Срок хранения инфраструктурных журналов определяется production-провайдером и должен быть минимально необходимым; рекомендуемый предел — 30 дней. Аналитические сроки задаются в кабинетах соответствующих сервисов.", "Применяются минимизация данных, read-only публичные API, allowlist tenant, ограничение частоты запросов, кэширование и запрет загрузки аналитики до consent."] },
      { title: "6. Права субъекта", paragraphs: ["Можно запросить сведения об обработке, доступ, исправление, удаление, ограничение, возражение и отзыв согласия, если соответствующее право применяется. Для отзыва аналитики очистите ключ job_ftch_consent в localStorage; для запросов свяжитесь с оператором.", "Жалоба может быть направлена в компетентный надзорный орган. Для пользователей РФ применяются требования 152-ФЗ; для лиц в ЕЭЗ — применимые положения GDPR."] },
      { title: "7. Данные в вакансиях и первоисточниках", paragraphs: ["Сервис индексирует сведения, которые источники сделали общедоступными для поиска работы: название роли, организацию, условия, географию, вознаграждение и ссылку. Контактные данные физических лиц не должны публиковаться сверх необходимого; при обнаружении лишних персональных данных запись удаляется или редактируется по обоснованному обращению.", "Оператор не получает право собственности на данные источника и не использует их для профилирования кандидатов, кредитного скоринга или иных решений, порождающих юридические последствия."] },
      { title: "8. Обращения, удаление и изменения", paragraphs: ["Правообладатель, субъект данных или представитель источника может потребовать исправления, удаления или прекращения индексирования, указав URL, основание и способ связи. Запрос рассматривается без неоправданной задержки; при споре доступ к записи может быть временно ограничен.", "Политика обновляется при изменении состава данных, аналитики или инфраструктуры. До публичного production-запуска владелец обязан заменить описание оператора на полное имя или наименование юридического лица, адрес и рабочий контакт."] },
    ] },
    cookies: { title: "Политика cookies и локального хранения", summary: "Что сохраняется в браузере и как управлять согласием.", sections: [
      { title: "Необходимое хранение", paragraphs: ["Сайт использует localStorage для темы, языка и записи job_ftch_consent. Эти значения нужны для сохранения выбранного интерфейса и не используются для рекламного профилирования."] },
      { title: "Аналитика", paragraphs: ["Google Analytics и Yandex Metrika загружаются только если заданы production-идентификаторы и пользователь разрешил аналитику. Отказ не влияет на доступ к сайту."] },
      { title: "Управление", paragraphs: ["Выбор можно изменить очисткой данных сайта в браузере. После очистки consent-баннер будет показан снова."] },
      { title: "Текущее состояние", paragraphs: ["Интеграции Google Analytics и Yandex Metrika предусмотрены кодом, но не работают без идентификаторов счётчиков. В локальной среде аналитика отключена. После production-настройки скрипт конкретного поставщика загружается только после согласия."] },
    ] },
    licensing: { title: "Лицензия", summary: "Условия использования кода и границы лицензирования данных.", sections: [
      { title: "Код", paragraphs: ["Исходный код job_ftch распространяется по лицензии MIT из файла LICENSE в корне репозитория. При копировании сохраняйте уведомление об авторских правах и текст лицензии."] },
      { title: "Данные и сторонние материалы", paragraphs: ["MIT не предоставляет права на тексты вакансий, товарные знаки, логотипы и содержимое сторонних источников. Такие материалы принадлежат их правообладателям и используются только для индексирования, ссылки на первоисточник и демонстрации работы pipeline."] },
      { title: "Отсутствие гарантий", paragraphs: ["Программное обеспечение предоставляется «как есть» без гарантий товарной пригодности, соответствия конкретной цели и отсутствия нарушений, в пределах, разрешённых законом."] },
      { title: "Лицензия не является разрешением на сбор", paragraphs: ["MIT разрешает использовать и изменять код, но не заменяет согласие владельца сайта, договор, лицензию на API или иное законное основание доступа. Пользователь самостоятельно определяет допустимость каждого источника, соблюдает его условия, robots.txt, ограничения частоты, авторские права и права изготовителя базы данных."] },
    ] },
    disclaimer: { title: "Отказ от ответственности", summary: "Ограничения точности вакансий, источников и автоматических решений.", sections: [
      { title: "Информационный характер", paragraphs: ["Сайт не является кадровым агентством, работодателем или оператором площадки вакансий. Он агрегирует публичные сигналы и не гарантирует актуальность, полноту, законность или доступность конкретной вакансии."] },
      { title: "Проверка первоисточника", paragraphs: ["Перед откликом самостоятельно проверьте работодателя, условия, дату, домен и контакт. Никогда не переводите деньги и не передавайте документы без проверки получателя."] },
      { title: "Автоматическая обработка", paragraphs: ["Классификация, дедупликация и оценка релевантности могут ошибаться. Результаты не являются юридической, финансовой, карьерной или миграционной консультацией и не должны быть единственным основанием значимого решения."] },
      { title: "Ответственность", paragraphs: ["В пределах, допускаемых применимым правом, сопровождающие проекта не отвечают за косвенные убытки, действия третьих лиц, недоступность источников и решения, принятые по данным сайта. Обязательные права потребителя и иные неотчуждаемые права не ограничиваются."] },
      { title: "Функции доступа и обхода защиты", paragraphs: ["Репозиторий содержит адаптеры браузера, прокси и стратегии обработки anti-bot сигналов как технический пример для тестирования собственных систем, разрешённого исследования и доступа, на который пользователь имеет право. Наличие такой функции не означает разрешение обходить авторизацию, CAPTCHA, платный доступ, блокировку, договорный запрет или иную меру защиты чужой системы.", "Сопровождающие не поручают и не контролируют действия самостоятельных пользователей. Пользователь несёт ответственность за конфигурацию, выбранные цели и законность получения и дальнейшего использования данных. Этот пункт не исключает ответственность сопровождающего там, где она прямо установлена законом."] },
      { title: "Удаление материала", paragraphs: ["Если вакансия, ссылка или описание нарушает право, содержит недостоверные либо лишние персональные данные, направьте владельцу репозитория URL и обоснование. Материал может быть скрыт на время проверки и удалён без признания нарушения."] },
    ] },
    terms: { title: "Правила использования", summary: "Допустимое использование сайта, API и материалов.", sections: [
      { title: "Разрешённое использование", paragraphs: ["Разрешены просмотр, поиск, ссылки на первоисточники, небольшие приватные интеграции и разумное использование read-only API с соблюдением лимитов и кэшированием."] },
      { title: "Запрещённые действия", paragraphs: ["Запрещены обход rate limits и технических ограничений, попытки доступа к закрытым данным, нагрузочные атаки, вредоносные payload, спам, массовые автоматические отклики, выдача проекта за работодателя и нарушение прав третьих лиц."] },
      { title: "API и доступность", paragraphs: ["Публичный API предоставляется без SLA, может изменяться, ограничиваться или временно отключаться ради безопасности. Не создавайте критическую зависимость без отдельного соглашения."] },
      { title: "Изменения и прекращение", paragraphs: ["Продолжение использования после публикации новой редакции означает принятие обновлённых правил в допустимой законом мере. Доступ может быть ограничен при злоупотреблении."] },
      { title: "Правомерность доступа", paragraphs: ["Пользователь запускает сбор только для общедоступных материалов либо при наличии разрешения, договора, лицензии, собственного тестового контура или иного законного основания. Запрещены получение учётных данных без согласия, обход авторизации и платного доступа, вмешательство в работу систем, копирование существенной части защищённой базы данных и обработка персональных данных без основания."] },
      { title: "Содержимое и уведомления", paragraphs: ["Тексты вакансий и обозначения принадлежат соответствующим правообладателям. Сервис хранит структурированное описание и ссылку для поиска и демонстрации pipeline, не подтверждает работодателя и вправе удалить запись по собственной инициативе или обоснованному уведомлению."] },
      { title: "Применимое право", paragraphs: ["К отношениям применяется право места деятельности оператора и обязательные нормы, применимые к пользователю и обработке данных. Споры сначала предлагается урегулировать письменным обращением. Ничто в правилах не лишает лицо права обратиться в суд или надзорный орган."] },
    ] },
    "fair-use": { title: "Fair use и приватная автоматизация", summary: "Правила для личных агентов, дайджестов и автоматизированного доступа.", sections: [
      { title: "Допустимые сценарии", paragraphs: ["Допустимы личный поиск, локальный агент, приватный дайджест, внутренний некоммерческий прототип и исследование качества данных при сохранении ссылки на первоисточник."] },
      { title: "Техническая добросовестность", paragraphs: ["Используйте API вместо scraping сайта, кэшируйте ответы минимум 15 минут, применяйте backoff, соблюдайте Retry-After и не распараллеливайте массовые запросы. Не обходите robots.txt, CAPTCHA, авторизацию и ограничения источников."] },
      { title: "Контроль человека", paragraphs: ["Автоматизация не должна самостоятельно отправлять отклики, сообщения работодателям, соглашаться с условиями или раскрывать персональные данные. Такие действия выполняются только после явного подтверждения человека для каждого адресата."] },
      { title: "Публичное и коммерческое повторное использование", paragraphs: ["Массовая перепубликация, создание конкурирующего публичного агрегатора, продажа набора данных или высокая нагрузка требуют отдельного разрешения и самостоятельной проверки лицензий источников."] },
      { title: "Статус проекта", paragraphs: ["Публичный сайт — пример работы open-source библиотеки, а не коммерческая услуга scraping-as-a-service. Проект не продаёт доступ к данным, не принимает заказы на обход защиты и не обещает доступность конкретного источника.", "Private automation означает запуск пользователем для личного поиска, локального исследования или внутреннего некоммерческого прототипа. Пользователь сам предоставляет инфраструктуру, конфигурацию и законные права доступа."] },
      { title: "Уважение технических и правовых ограничений", paragraphs: ["Не используйте проект для обхода CAPTCHA, авторизации, paywall, блокировки аккаунта или IP, если владелец ресурса не дал разрешение либо такое действие не допускается законом. Остановите сбор при запрете, жалобе, ошибках 401/403/429, требовании CAPTCHA или очевидной деградации ресурса; используйте официальный API, минимальную частоту и кэш."] },
      { title: "Минимизация и хранение", paragraphs: ["Собирайте только поля, необходимые для личного поиска вакансий; не создавайте досье на людей, не обогащайте контакты и не храните исходные страницы дольше необходимого. Не публикуйте полный корпус или существенную часть базы источника. Сохраняйте атрибуцию и прямую ссылку."] },
    ] },
  },
  en: {},
};

legalDocuments.en = {
  privacy: { title: "Privacy and personal data policy", summary: "What the site may process, why, on which basis, and how data-subject rights can be exercised.", sections: legalDocuments.ru.privacy.sections.map((section, index) => ({ title: ["1. Controller and scope", "2. Data categories", "3. Purposes and legal bases", "4. Recipients and international transfers", "5. Retention, deletion and security", "6. Data-subject rights", "7. Vacancy and source data", "8. Requests, removal and changes"][index], paragraphs: [
    [common.en.effective, common.en.operator, "This policy applies to the public job_ftch website, read-only API and documentation. It does not govern third-party vacancy sites or Telegram."],
    ["There is no user registration. The site may process IP addresses and security logs at infrastructure level; URL, referrer, browser, device and pseudonymous events only after analytics consent; language, theme and consent choices locally in the browser.", "The site does not request payment, passport, health, biometric or other special-category data."],
    ["Technical logs support delivery, abuse prevention, diagnostics and API security under operational necessity and legitimate security interests. Analytics relies on explicit consent.", "Refusing or withdrawing consent does not restrict core access."],
    ["When configured, Google Analytics and Yandex Metrika may receive analytics data under their terms. Their scripts do not load before consent. Hosting and network providers may process technical logs.", "The operator must verify hosting location and transfer safeguards before production analytics is enabled."],
    ["Browser preferences remain until cleared. Infrastructure logs should be retained only as necessary, with 30 days as the recommended ceiling. Analytics retention is configured with each provider.", "Controls include data minimisation, read-only APIs, tenant allowlisting, rate limits, caching and prior consent."],
    ["Where applicable, users may request information, access, correction, erasure, restriction, objection and consent withdrawal. Delete job_ftch_consent from localStorage to reset analytics consent and contact the controller for other requests.", "Users may complain to a competent authority. Russian users are covered by applicable 152-FZ rules; EEA users by applicable GDPR provisions."],
    ["The service indexes job-search information made public by sources: role, organisation, terms, geography, compensation and source URL. Personal contact details must not be republished beyond necessity and may be removed or redacted after a substantiated request.", "The operator acquires no ownership of source data and does not use it for candidate profiling, credit scoring or decisions producing legal effects."],
    ["A rights holder, data subject or source representative may request correction, removal or de-indexing by identifying the URL, legal basis and contact method. Access may be restricted while a dispute is reviewed.", "Before public production deployment, the owner must replace the controller description with a full legal name, address and working privacy contact."],
  ][index] })) },
  cookies: { title: "Cookies and local storage policy", summary: "What is stored in the browser and how consent is controlled.", sections: [
    { title: "Essential storage", paragraphs: ["The site uses localStorage for theme, language and job_ftch_consent. These values preserve interface choices and are not used for advertising profiles."] },
    { title: "Analytics", paragraphs: ["Google Analytics and Yandex Metrika load only when production IDs are configured and analytics consent was granted. Refusal does not affect access."] },
    { title: "Control", paragraphs: ["Clear this site's browser data to reset the choice. The consent notice will appear again."] },
    { title: "Current status", paragraphs: ["Google Analytics and Yandex Metrika integrations exist in code but do not operate without counter IDs. Analytics is disabled locally. In production each provider script loads only after consent."] },
  ] },
  licensing: { title: "License", summary: "Code licensing and the limits that apply to third-party data.", sections: [
    { title: "Code", paragraphs: ["job_ftch source code is distributed under the MIT License in the repository-root LICENSE file. Copies must retain the copyright notice and license text."] },
    { title: "Data and third-party material", paragraphs: ["MIT grants no rights to vacancy text, trademarks, logos or third-party content. Those remain with their owners and are used only for indexing, source linking and pipeline demonstration."] },
    { title: "No warranty", paragraphs: ["The software is provided as is, without warranties of merchantability, fitness for a particular purpose or non-infringement, to the extent permitted by law."] },
    { title: "No permission to collect", paragraphs: ["The MIT licence permits use and modification of code; it does not replace a site owner's permission, contract, API licence or other lawful access basis. Each user must assess every source and respect its terms, robots.txt, rate limits, copyright and database rights."] },
  ] },
  disclaimer: { title: "Disclaimer", summary: "Accuracy limits for vacancies, sources and automated decisions.", sections: [
    { title: "Information only", paragraphs: ["The site is not a recruitment agency, employer or vacancy platform operator. It aggregates public signals and does not guarantee a vacancy's accuracy, completeness, legality or availability."] },
    { title: "Verify the source", paragraphs: ["Verify the employer, terms, date, domain and contact before applying. Never transfer money or identity documents without confirming the recipient."] },
    { title: "Automated processing", paragraphs: ["Classification, deduplication and relevance scoring can be wrong. Results are not legal, financial, career or immigration advice and must not be the sole basis of a significant decision."] },
    { title: "Liability", paragraphs: ["To the extent permitted by law, maintainers are not liable for indirect loss, third-party conduct, source downtime or decisions based on site data. Mandatory consumer and other non-waivable rights remain unaffected."] },
    { title: "Access and protection-handling capabilities", paragraphs: ["Browser, proxy and anti-bot signal adapters are technical examples for testing systems the user owns, authorised security research and access the user is legally entitled to perform. Their presence does not authorise bypassing authentication, CAPTCHA, paywalls, blocks, contractual restrictions or another party's technical protection.", "Maintainers do not direct or control independent deployments. Users remain responsible for configuration, targets and lawful acquisition and reuse of data. This clause does not exclude liability where exclusion is prohibited by law."] },
    { title: "Removal requests", paragraphs: ["If a vacancy, link or description infringes rights or contains inaccurate or unnecessary personal data, send the repository owner the URL and basis. Material may be hidden during review and removed without admission of liability."] },
  ] },
  terms: { title: "Terms of use", summary: "Acceptable use of the website, API and materials.", sections: [
    { title: "Permitted use", paragraphs: ["Viewing, searching, source links, small private integrations and reasonable read-only API use are permitted when limits and caching are respected."] },
    { title: "Prohibited use", paragraphs: ["Do not bypass rate or access controls, seek private data, run load attacks, send malicious payloads or spam, submit applications at scale, impersonate an employer or violate third-party rights."] },
    { title: "API and availability", paragraphs: ["The public API has no SLA and may change, be limited or be disabled for security. Do not create a critical dependency without a separate agreement."] },
    { title: "Changes and suspension", paragraphs: ["Continued use after a published revision constitutes acceptance where legally effective. Abusive access may be suspended."] },
    { title: "Lawful access", paragraphs: ["Collection may target public material or systems covered by permission, contract, licence, an owned test environment or another lawful basis. Credential theft, authentication or paywall bypass, system interference, extraction of a substantial protected database and processing personal data without a legal basis are prohibited."] },
    { title: "Content and notices", paragraphs: ["Vacancy text and marks remain the property of their owners. The service stores structured descriptions and source links for search and pipeline demonstration, does not endorse an employer, and may remove records after notice or on its own initiative."] },
    { title: "Governing rules", paragraphs: ["The law of the operator's place of establishment and mandatory rules applicable to the user and data processing apply. Parties should first attempt written resolution. Nothing removes a person's right to contact a court or supervisory authority."] },
  ] },
  "fair-use": { title: "Fair use and private automation", summary: "Rules for personal agents, digests and automated access.", sections: [
    { title: "Permitted scenarios", paragraphs: ["Personal search, local agents, private digests, internal non-commercial prototypes and data-quality research are allowed when source links are preserved."] },
    { title: "Technical good faith", paragraphs: ["Prefer the API over site scraping, cache for at least 15 minutes, use backoff, honour Retry-After and avoid bulk parallel requests. Never bypass robots.txt, CAPTCHA, authentication or source restrictions."] },
    { title: "Human control", paragraphs: ["Automation must not independently submit applications, message employers, accept terms or disclose personal data. Each such action requires explicit human approval for the specific recipient."] },
    { title: "Public and commercial reuse", paragraphs: ["Bulk republication, a competing public aggregator, dataset sales or high-volume use require separate permission and an independent review of source licences."] },
    { title: "Project status", paragraphs: ["The public site demonstrates an open-source library; it is not a commercial scraping-as-a-service offering. The project does not sell data access, accept protection-bypass commissions or promise access to any source.", "Private automation means personal job search, local research or an internal non-commercial prototype. The user supplies infrastructure, configuration and lawful access rights."] },
    { title: "Technical and legal limits", paragraphs: ["Do not use the project to bypass CAPTCHA, authentication, paywalls, account or IP blocks unless the resource owner authorised it or applicable law clearly permits it. Stop collection after a prohibition, complaint, 401/403/429 response, CAPTCHA demand or evident service degradation; prefer official APIs, low request rates and caching."] },
    { title: "Minimisation and retention", paragraphs: ["Collect only fields needed for private vacancy search; do not build dossiers on people, enrich personal contacts or retain source pages longer than necessary. Do not publish a complete corpus or substantial part of a source database. Preserve attribution and direct links."] },
  ] },
};
