"""job_ftch owned-browser hook for the vendored parity lab.

The hook receives only a loopback URL generated by paritylab.  It must not be
used to target third-party sites.
"""

from __future__ import annotations

import asyncio
import contextlib
import os
from typing import Any

from paritylab.clients.base import ClientHookContext


async def _wait_for_optional(page: Any, expression: str, timeout_ms: int) -> None:
    wait_for_function = getattr(page, "wait_for_function", None)
    if not callable(wait_for_function):
        await asyncio.sleep(timeout_ms / 1000)
        return
    try:
        await wait_for_function(expression, timeout=timeout_ms)
    except Exception:
        return


async def _exercise_parity_page(page: Any) -> dict[str, Any]:
    await _wait_for_optional(page, "window.__parityLabReady === true", 8000)

    mouse = getattr(page, "mouse", None)
    if mouse is not None:
        move = getattr(mouse, "move", None)
        wheel = getattr(mouse, "wheel", None)
        if callable(move):
            await move(96, 112)
            await move(174, 151)
            await move(248, 226)
        if callable(wheel):
            await wheel(0, 360)

    locator = getattr(page, "locator", None)
    if callable(locator):
        with contextlib.suppress(Exception):
            await locator("#interaction-target").click(timeout=3000)
        with contextlib.suppress(Exception):
            await locator("#interaction-input").fill("job-ftch-owned-client", timeout=3000)
    else:
        click = getattr(page, "click", None)
        if callable(click):
            with contextlib.suppress(Exception):
                await click("#interaction-target")

    keyboard = getattr(page, "keyboard", None)
    if keyboard is not None:
        press = getattr(keyboard, "press", None)
        if callable(press):
            await press("Tab")

    evaluate = getattr(page, "evaluate", None)
    result: Any = None
    if callable(evaluate):
        await evaluate("window.scrollTo(0, 520)")
        await evaluate("window.parityLabFinish && window.parityLabFinish()")
        await _wait_for_optional(page, "window.__parityLabDone === true", 8000)
        try:
            result = await evaluate("window.__parityLabResult || null")
        except Exception:
            result = None
    return {"pageResult": result}


async def run_owned_browser(context: ClientHookContext) -> dict[str, Any]:
    from job_ftch.application.registry import resolve_bypass
    from job_ftch.infrastructure.bypass.context import BypassContext
    from job_ftch.infrastructure.sources.browser_utils import navigate, open_page

    tier = os.environ.get("JOB_FTCH_PARITY_TIER", "patchright_browser").strip()
    strategy_name = os.environ.get("JOB_FTCH_PARITY_STRATEGY", "auto").strip()
    strategy = resolve_bypass(strategy_name, {})
    bypass_ctx = await BypassContext.for_url(
        context.url,
        config={"_allow_private_selfcheck_fixture": True, "skip_ssl": True},
    )
    bind_context = getattr(strategy, "bind_context", None)
    if callable(bind_context):
        bind_context(bypass_ctx)
    escalate_to = getattr(strategy, "escalate_to", None)
    if callable(escalate_to):
        escalate_to(tier)

    browser_config: dict[str, Any] = {
        "url": context.url,
        "headless": os.environ.get("JOB_FTCH_PARITY_HEADED", "") not in {"1", "true", "True"},
        "persistent_context": os.environ.get("JOB_FTCH_PARITY_PERSISTENT", "")
        in {"1", "true", "True"},
        "skip_ssl": True,
        "challenge_retries": 0,
        "_allow_private_selfcheck_fixture": True,
        "_bypass_context": bypass_ctx,
    }
    prepare_browser_config = getattr(strategy, "prepare_browser_config", None)
    if callable(prepare_browser_config):
        browser_config = prepare_browser_config(browser_config)

    async with open_page(browser_config, bypass_strategy=strategy) as page:
        await navigate(
            page,
            context.url,
            {
                "_allow_private_selfcheck_fixture": True,
                "skip_ssl": True,
                "wait_until": "domcontentloaded",
                "challenge_retries": 0,
            },
        )
        page_result = await _exercise_parity_page(page)

    context.artifacts_dir.mkdir(parents=True, exist_ok=True)
    return {
        "adapter": "job_ftch",
        "tier": tier,
        "strategy": strategy_name,
        **page_result,
    }
