from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from paritylab.catalog import load_catalog  # noqa: E402


def render_coverage() -> str:
    catalog = load_catalog()
    coverage = catalog.coverage()
    lines = [
        "# Coverage ledger",
        "",
        "Generated from `paritylab/catalog/catalog.json`. Do not edit this file manually.",
        "",
        f"Catalog version: `{catalog.version}`.",
        "",
        f"Weighted surface coverage: **{coverage['weighted_surface_coverage']:.1%}**.",
        "",
        "| Status | Surfaces |",
        "|---|---:|",
    ]
    lines.extend(
        f"| `{status}` | {count} |" for status, count in coverage["surface_status"].items()
    )
    lines.extend(
        ["", "## Surfaces", "", "| Family | Surface | Status | Stability |", "|---|---|---|---|"]
    )
    lines.extend(
        f"| {item.family} | `{item.id}` — {item.title} | {item.status.value} | {item.stability.value} |"
        for item in sorted(catalog.surfaces, key=lambda value: (value.family, value.id))
    )
    lines.extend(
        [
            "",
            "## Inventory",
            "",
            f"- Findings: {coverage['finding_count']}",
            f"- Mechanics: {coverage['mechanic_count']}",
            f"- Countermeasures: {coverage['countermeasure_count']}",
            "",
        ]
    )
    return "\n".join(lines)


def render_mechanics() -> str:
    catalog = load_catalog()
    countermeasures = {item.id: item for item in catalog.countermeasures}
    lines = [
        "# Detection and countermeasure encyclopedia",
        "",
        "Generated from the versioned catalog. Entries describe controlled, owned-lab validation; they are not instructions for attacking third-party services.",
        "",
    ]
    for item in sorted(catalog.mechanics, key=lambda value: (value.category, value.id)):
        lines.extend(
            [
                f"## {item.title}",
                "",
                f"- ID: `{item.id}`",
                f"- Category: `{item.category}`",
                f"- Coverage: `{item.status.value}`",
                f"- Description: {item.description}",
                f"- Observable consequences: {', '.join(item.observable_consequences)}",
                f"- Surfaces: {', '.join(f'`{surface}`' for surface in item.surfaces)}",
                f"- Countermeasures: {', '.join(countermeasures[cm].title for cm in item.countermeasures)}",
                f"- Residual risk: {item.residual_risk}",
                "",
            ]
        )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()
    root = ROOT
    outputs = {
        root / "docs" / "COVERAGE.md": render_coverage(),
        root / "docs" / "MECHANICS.md": render_mechanics(),
    }
    if args.json:
        print(json.dumps(load_catalog().coverage(), indent=2, sort_keys=True))
    stale = [
        path
        for path, content in outputs.items()
        if not path.exists() or path.read_text(encoding="utf-8") != content
    ]
    if args.check:
        if stale:
            print("stale generated catalog docs: " + ", ".join(str(path) for path in stale))
            return 1
        return 0
    for path, content in outputs.items():
        path.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
