"""Run-based snapshot filter: drop items seen in the previous run of this source.

Per ADR-031, the filter is wired to the ``jf_source_snapshots`` table.
A ``RawItem`` is dropped when its ``stable_id`` appears in the most recent run
of the same ``source_id`` (the source already yielded it; do not process again).

This node is *not* a duplicate detector. Cross-source and forever-remembered
duplicates are handled by ``DedupNode`` (see ADR-005).
"""

from __future__ import annotations

import hashlib
from collections import defaultdict
from typing import TYPE_CHECKING

import structlog

from job_ftch.application.drops import RawItemDropped
from job_ftch.domain.triage import TriageRejectionReason

if TYPE_CHECKING:
    from job_ftch.application.contracts import Store
    from job_ftch.domain.models import RawItem

logger = structlog.get_logger(__name__)


def _content_hash(item: RawItem) -> str:
    """Stable hash of the item content used for change detection (ADR-031 §decision-3)."""
    parts = [
        str(item.url or ""),
        str(item.text or ""),
        str(item.source_name or ""),
    ]
    payload = "|".join(parts).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def _derive_source_id(item: RawItem) -> str:
    """Return the snapshot source id derived from a raw item.

    Mirrors ``source_spec_identifier`` for runtime items that already carry
    ``source_kind`` and ``source_name``. Falls back to ``source_name`` alone
    when kind is missing.
    """
    name = str(item.source_name or item.source_kind or "unknown")
    kind = (
        str(item.source_kind.value) if hasattr(item.source_kind, "value") else str(item.source_kind)
    )
    if kind and kind != "unknown":
        return f"{kind}:{name}"
    return name


class SnapshotFilterNode:
    """Drop raw items whose ``stable_id`` was in the last run of this source.

    The node is added to the pipeline once and shared across all sources in
    the same run. It auto-binds the per-source snapshot lazily on the first
    item it sees from a given ``source_id`` (derived from the item itself).

    Lifecycle per pipeline run::

        node = SnapshotFilterNode(store, tenant_id=..., run_id=..., ttl_days=7)
        for item in items_from_all_sources:
            await node.process(item)   # drops ALREADY_SEEN, accumulates rows per source
        await node.save_and_purge()    # persists rows for all sources and purges new runs
    """

    DEFAULT_TTL_DAYS = 7

    def __init__(
        self,
        store: Store,
        *,
        tenant_id: str,
        run_id: str,
        ttl_days: int = DEFAULT_TTL_DAYS,
        fail_open: bool = False,
    ) -> None:
        if not run_id:
            msg = "SnapshotFilterNode requires a non-empty run_id"
            raise ValueError(msg)
        self._store = store
        self._tenant_id = tenant_id
        self._run_id = run_id
        self._ttl_days = ttl_days
        self._fail_open = fail_open

        # source_id → stable_id/content_hash from the last completed run.
        self._last_run_hashes: dict[str, dict[str, str]] = {}
        # source_id → list of (stable_id, item_hash, item_json) for the current run
        self._current_rows: dict[str, list[tuple[str, str, str]]] = defaultdict(list)
        self._dropped_last_run = 0
        self._bound_sources: set[str] = set()

    @property
    def dropped_last_run(self) -> int:
        """Counter of items dropped because they were in the last run of their source."""
        return self._dropped_last_run

    @property
    def bound_sources(self) -> frozenset[str]:
        """Source ids that the node has bound during this run (read-only)."""
        return frozenset(self._bound_sources)

    def set_run_id(self, run_id: str) -> None:
        """Replace the run_id used by ``save_and_purge``.

        TenantRunner calls this after ``builder.run_async()`` to align the
        snapshot's run_id with ``RunSummary.source_run_id`` generated by the
        pipeline. The value must be non-empty.
        """
        if not run_id:
            msg = "set_run_id requires a non-empty run_id"
            raise ValueError(msg)
        self._run_id = run_id

    async def _ensure_bound(self, source_id: str) -> dict[str, str]:
        if source_id in self._last_run_hashes:
            return self._last_run_hashes[source_id]
        try:
            snapshot = await self._store.get_last_run_snapshot_hashes(self._tenant_id, source_id)
        except Exception:
            logger.warning(
                "snapshot_read_failed",
                tenant_id=self._tenant_id,
                source_id=source_id,
                fail_open=self._fail_open,
                exc_info=True,
            )
            if self._fail_open:
                snapshot = {}
            else:
                raise
        self._last_run_hashes[source_id] = snapshot
        self._bound_sources.add(source_id)
        return snapshot

    async def process(self, item: RawItem) -> RawItem | None:
        source_id = _derive_source_id(item)
        sid = str(item.stable_id or "")
        if not sid:
            return item

        item_hash = _content_hash(item)
        last_run = await self._ensure_bound(source_id)
        # A complete snapshot must contain every item observed in this run,
        # including items dropped as unchanged.  Otherwise a run consisting
        # mostly of unchanged postings would replace a full snapshot with only
        # its changed tail and force needless reprocessing next time.
        item_json = item.model_dump_json()
        self._current_rows[source_id].append((sid, item_hash, item_json))
        if last_run.get(sid) == item_hash:
            self._dropped_last_run += 1
            raise RawItemDropped(
                reason=TriageRejectionReason.ALREADY_SEEN,
                details=f"Seen in last run of source '{source_id}' (run-based snapshot).",
                item=item,
                stage=self.__class__.__name__,
            )

        return item

    async def save_and_purge(
        self,
        *,
        source_run_complete: bool = True,
        completed_source_ids: frozenset[str] | None = None,
    ) -> None:
        """Persist this run's rows for every bound source and purge new runs.

        Per ADR-031: called once per pipeline run, after the ``process()`` loop.
        A source with no new rows still has its purge executed (consistent TTL).
        """
        if not source_run_complete:
            self._current_rows.clear()
            logger.warning("snapshot_commit_skipped_incomplete_source_run", run_id=self._run_id)
            return

        for source_id, rows in self._current_rows.items():
            if completed_source_ids is not None and source_id not in completed_source_ids:
                logger.warning(
                    "snapshot_commit_skipped_incomplete_source",
                    run_id=self._run_id,
                    source_id=source_id,
                )
                continue
            if not rows:
                continue
            await self._store.save_snapshot_rows(
                self._tenant_id,
                source_id,
                self._run_id,
                tuple(rows),
            )
            logger.info(
                "snapshot_saved",
                source=source_id,
                run_id=self._run_id,
                items=len(rows),
            )

        if self._ttl_days > 0:
            for source_id in self._bound_sources:
                if completed_source_ids is not None and source_id not in completed_source_ids:
                    continue
                deleted = await self._store.purge_old_snapshots(
                    self._tenant_id,
                    source_id=source_id,
                    older_than_days=self._ttl_days,
                )
                if deleted:
                    logger.info(
                        "snapshot_purged",
                        source=source_id,
                        older_than_days=self._ttl_days,
                        deleted=deleted,
                    )


__all__ = ["SnapshotFilterNode", "_content_hash"]


def _legacy_factory(  # pragma: no cover - kept for type-checker compatibility
    *args: object,
    **kwargs: object,
) -> SnapshotFilterNode:
    """Deprecated factory kept only to surface a clear error to new call sites."""
    raise NotImplementedError(
        "SnapshotFilterNode(snapshot_by_source=...) is removed. "
        "Use SnapshotFilterNode(store, tenant_id=..., run_id=...) and call "
        "process() per item and save_and_purge() once at end of run. See ADR-031."
    )
