"""Generate graph reference documentation from the node registry.

Outputs:
  - docs/nodes/reference.md    -- per-node manifest summary
  - docs/pipelines/graphs.md   -- per-pipeline graph summary

Both files carry a GENERATED marker so CI can detect manual edits.
"""

from __future__ import annotations

import hashlib
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
PIPELINES_DIR = ROOT / "config" / "pipelines"
NODES_DOC = ROOT / "docs" / "nodes" / "reference.md"
GRAPHS_DOC = ROOT / "docs" / "pipelines" / "graphs.md"

_MARKER = "<!-- GENERATED by scripts/build_graph_reference.py - DO NOT EDIT -->"


def _load_manifests() -> list[dict[str, Any]]:
    """Import all node modules to populate the registry, then dump manifests."""
    # Trigger node registration
    import job_ftch.nodes  # noqa: F401
    from job_ftch.application.graph.registry import manifests

    result = []
    for m in manifests():
        result.append(
            {
                "node_id": m.node_id,
                "input_type": m.input_type,
                "output_type": m.output_type,
                "implementation_version": m.implementation_version,
                "capabilities": list(m.capabilities),
                "allowed_execution": [str(e) for e in m.allowed_execution],
                "allowed_effects": [str(e) for e in m.allowed_effects],
                "mutates_payload": m.mutates_payload,
                "resource_requirements": list(m.resource_requirements),
                "params": {
                    name: {
                        "type": spec.type_name,
                        "default": spec.default,
                        "required": spec.required,
                    }
                    for name, spec in (m.param_schema or {}).items()
                }
                if m.param_schema
                else {},
            }
        )
    return sorted(result, key=lambda m: m["node_id"])


def _compile_graphs() -> list[dict[str, Any]]:
    """Load and compile every pipeline YAML."""
    from job_ftch.application.graph import compile_graph, load_graph

    results = []
    for path in sorted(PIPELINES_DIR.glob("*.yaml")):
        try:
            spec = load_graph(path)
            graph = compile_graph(spec)
            results.append(
                {
                    "file": path.name,
                    "name": graph.spec.name,
                    "version": graph.spec.version,
                    "graph_hash": graph.graph_hash,
                    "node_count": len(graph.spec.nodes),
                    "execution_order": list(graph.execution_order),
                    "metadata": graph.spec.metadata,
                }
            )
        except Exception as exc:
            results.append(
                {
                    "file": path.name,
                    "error": str(exc),
                }
            )
    return results


def _render_nodes_md(manifests: list[dict[str, Any]]) -> str:
    lines = [
        "---",
        'title: "Generated node reference"',
        'description: "Generated reference of registered graph nodes and manifests."',
        "updated: 2026-07-26",
        "---",
        _MARKER,
        "",
        "# Node Reference",
        "",
        f"Generated: {datetime.now(UTC).isoformat()}",
        f"Total registered nodes: {len(manifests)}",
        "",
        "| Node | Input | Output | Version | Capabilities |",
        "|------|-------|--------|---------|-------------|",
    ]
    for m in manifests:
        caps = ", ".join(m["capabilities"]) or "-"
        lines.append(
            f"| {m['node_id']} "
            f"| {m['input_type']} "
            f"| {m['output_type']} "
            f"| {m['implementation_version']} "
            f"| {caps} |"
        )

    lines.append("")
    lines.append("## Node Details")
    lines.append("")
    for m in manifests:
        lines.append(f"### {m['node_id']}")
        lines.append("")
        lines.append(f"- Input: `{m['input_type']}`")
        lines.append(f"- Output: `{m['output_type']}`")
        lines.append(f"- Version: {m['implementation_version']}")
        lines.append(f"- Mutates payload: {m['mutates_payload']}")
        if m["params"]:
            lines.append("- Parameters:")
            for name, spec in m["params"].items():
                req = "required" if spec["required"] else f"default={spec['default']}"
                lines.append(f"  - `{name}` ({spec['type']}, {req})")
        if m["resource_requirements"]:
            lines.append(f"- Resources: {', '.join(m['resource_requirements'])}")
        lines.append("")

    return "\n".join(lines)


def _render_graphs_md(graphs: list[dict[str, Any]]) -> str:
    lines = [
        "---",
        'title: "Generated pipeline graph reference"',
        'description: "Generated reference of configured pipeline graphs and graph hashes."',
        "updated: 2026-07-26",
        "---",
        _MARKER,
        "",
        "# Pipeline Graphs",
        "",
        f"Generated: {datetime.now(UTC).isoformat()}",
        f"Total graphs: {len(graphs)}",
        "",
        "| File | Name | Version | Hash | Nodes |",
        "|------|------|---------|------|-------|",
    ]
    for g in graphs:
        if "error" in g:
            lines.append(f"| {g['file']} | ERROR | - | - | {g['error'][:60]} |")
        else:
            hash_short = g["graph_hash"][:12]
            lines.append(
                f"| {g['file']} | {g['name']} | {g['version']} | {hash_short} | {g['node_count']} |"
            )

    lines.append("")
    lines.append("## Graph Details")
    lines.append("")
    for g in graphs:
        if "error" in g:
            continue
        lines.append(f"### {g['file']}")
        lines.append("")
        lines.append(f"- Name: {g['name']}")
        lines.append(f"- Version: {g['version']}")
        lines.append(f"- Hash: `{g['graph_hash']}`")
        lines.append(f"- Execution order: {' -> '.join(g['execution_order'])}")
        lines.append("")

    return "\n".join(lines)


def _content_hash(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def main() -> int:
    manifests = _load_manifests()
    graphs = _compile_graphs()

    nodes_md = _render_nodes_md(manifests)
    graphs_md = _render_graphs_md(graphs)

    NODES_DOC.parent.mkdir(parents=True, exist_ok=True)
    NODES_DOC.write_text(nodes_md, encoding="utf-8")
    print(f"Node reference: {NODES_DOC}")

    GRAPHS_DOC.parent.mkdir(parents=True, exist_ok=True)
    GRAPHS_DOC.write_text(graphs_md, encoding="utf-8")
    print(f"Graph reference: {GRAPHS_DOC}")

    print(f"Registered nodes: {len(manifests)}")
    print(f"Pipeline graphs: {len(graphs)}")
    errors = [g for g in graphs if "error" in g]
    if errors:
        print(f"Graphs with errors: {len(errors)}")
        for g in errors:
            print(f"  {g['file']}: {g['error']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
