"""Verify that generated documentation files match their source of truth.

Regenerates the docs in memory and compares against the on-disk version.
Exits non-zero if any generated file has been manually edited.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
_MARKER = "<!-- GENERATED by scripts/build_graph_reference.py - DO NOT EDIT -->"

GENERATED_FILES = [
    ROOT / "docs" / "nodes" / "reference.md",
    ROOT / "docs" / "pipelines" / "graphs.md",
]


def _normalize_content(text: str) -> str:
    """Strip timestamp lines so only structural content is compared.

    Generated files contain a timestamp that changes on every run.
    The check should detect structural edits, not stale timestamps.
    """
    lines = []
    for line in text.splitlines():
        # Skip the Generated: timestamp line
        if line.startswith("Generated:"):
            continue
        lines.append(line)
    return "\n".join(lines)


def main() -> int:
    missing: list[str] = []
    tampered: list[str] = []

    for path in GENERATED_FILES:
        if not path.exists():
            missing.append(str(path.relative_to(ROOT)))
            continue
        content = path.read_text(encoding="utf-8")
        if _MARKER not in content:
            tampered.append(str(path.relative_to(ROOT)))

    if missing:
        print("Missing generated files (run scripts/build_graph_reference.py):")
        for name in missing:
            print(f"  {name}")

    if tampered:
        print("Generated files with removed GENERATED marker (do not edit these):")
        for name in tampered:
            print(f"  {name}")

    if missing or tampered:
        return 1

    # Regenerate in memory and compare normalized content
    sys.path.insert(0, str(ROOT))
    from scripts.build_graph_reference import (
        _compile_graphs,
        _load_manifests,
        _render_graphs_md,
        _render_nodes_md,
    )

    manifests = _load_manifests()
    graphs = _compile_graphs()

    fresh_nodes = _normalize_content(_render_nodes_md(manifests))
    fresh_graphs = _normalize_content(_render_graphs_md(graphs))

    on_disk_nodes = _normalize_content(
        (ROOT / "docs" / "nodes" / "reference.md").read_text(encoding="utf-8")
    )
    on_disk_graphs = _normalize_content(
        (ROOT / "docs" / "pipelines" / "graphs.md").read_text(encoding="utf-8")
    )

    drifted: list[str] = []
    if fresh_nodes != on_disk_nodes:
        drifted.append("docs/nodes/reference.md")
    if fresh_graphs != on_disk_graphs:
        drifted.append("docs/pipelines/graphs.md")

    if drifted:
        print("Generated docs are stale (run scripts/build_graph_reference.py):")
        for name in drifted:
            print(f"  {name}")
        return 1

    print("Generated docs are up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
