"""Domain layer - pure models, zero I/O. Entities, value objects, domain rules."""

from job_ftch.domain.assessment import AssessedJob, DecisionResult, WorkState
from job_ftch.domain.candidate import CandidateIdentity, CandidateProfile, CandidateResumeSnapshot
from job_ftch.domain.contracts import draft_to_record, job_to_draft, job_to_record
from job_ftch.domain.dedup import (
    DedupKeyKind,
    DuplicateRecord,
    DuplicateRejectionReason,
    RememberedDedupKey,
    dedup_company_for_raw_item,
    dedup_content_key_for_raw_item,
    dedup_similarity_text_for_raw_item,
    dedup_text_for_raw_item,
    dedup_title_for_raw_item,
    dedup_url_for_raw_item,
    processed_key_for_raw_item,
    processed_key_for_url,
)
from job_ftch.domain.enrichment import EnrichmentTask
from job_ftch.domain.evidence import (
    ClaimAssessment,
    ClaimKind,
    ClaimParameters,
    EvidenceAtom,
    EvidenceBundle,
    EvidencePolarity,
    aggregate_bundle,
    aggregate_claim,
)
from job_ftch.domain.experiment import RelevanceCard
from job_ftch.domain.filter_profile import FilterProfile
from job_ftch.domain.job_group import (
    JobGroup,
    SourceAttribution,
    compute_content_version,
    compute_group_id,
    compute_identity_fingerprint,
    create_job_group,
    merge_job_into_group,
    merge_jobs,
    remove_job_from_group,
)
from job_ftch.domain.job_quality import (
    ExtractionRejectionReason,
    JobReviewReason,
    JobValidationRejectionReason,
)
from job_ftch.domain.lineage import JobLineage, build_job_lineage
from job_ftch.domain.models import (
    CandidateSpan,
    CompensationPeriod,
    CompensationRange,
    EmploymentType,
    EvidenceProvenance,
    Job,
    JobDraft,
    JobExtractionStatus,
    JobnessDecision,
    JobRecord,
    JobStatus,
    LanguageCode,
    MatchDecision,
    OntologySnapshot,
    PageKind,
    PostType,
    ProfileMatchScore,
    ProvenanceTrail,
    RawItem,
    RiskLevel,
    Seniority,
    SkillTag,
    SourceKind,
    StructuredSourceEvidence,
    WorkMode,
)
from job_ftch.domain.observation import ObservationLedgerEntry, content_hash_for_raw_item
from job_ftch.domain.ontology_graph import (
    CompiledOntology,
    CompiledOntologyRelation,
    CompiledOntologyTerm,
    ExtractedOntologyClaim,
    ExtractedRoleSkillEdge,
    MaterializedOntologyTerms,
    OntologyEdge,
    OntologyEvidence,
    OntologyNode,
    OntologyTermStat,
    ShotOntologyExtraction,
    ShotOntologyGraph,
)
from job_ftch.domain.outbox import (
    DeliveryEnvelope,
    OutboxRecord,
    OutboxState,
    delivery_envelope_from_record,
    delivery_idempotency_key,
)
from job_ftch.domain.presentable import PresentableJob
from job_ftch.domain.profile import (
    CompensationExpectation,
    ProfileCatalog,
    ProfileWeights,
    SearchProfile,
)
from job_ftch.domain.quarantine import QuarantinedRawItem, RawItemRejectionReason
from job_ftch.domain.rejected import RejectedItem, RejectedOutcome
from job_ftch.domain.relevance import RelevanceClassification, RelevanceEvidenceClassification
from job_ftch.domain.resolution import ResolutionTask
from job_ftch.domain.runtime_profile import ManagedCandidateProfile
from job_ftch.domain.runtime_source import (
    RuntimeSourceRecord,
    source_spec_identifier,
    source_spec_locator,
    source_spec_name,
)
from job_ftch.domain.shot_extraction import RelevanceKeyword, ShotExtraction
from job_ftch.domain.source_assessment import (
    AssessmentConfidence,
    FreshnessAssessment,
    SourceAssessmentResult,
    SourceCapabilities,
    SourceEvidence,
)
from job_ftch.domain.source_health import SourceHealth
from job_ftch.domain.source_identity import (
    AcquisitionTransport,
    ObservationKind,
    SourceFamily,
    SourceIdentity,
    source_identity_for_parts,
    source_identity_for_raw_item,
)
from job_ftch.domain.source_outcomes import SourceOutcome
from job_ftch.domain.source_spec import CareerSiteSpec
from job_ftch.domain.tenant import OutputSpec, ScheduleSpec, TenantConfig, TenantInfo
from job_ftch.domain.triage import TriageRejectionReason

__all__ = [
    "AssessmentConfidence",
    "AcquisitionTransport",
    "AssessedJob",
    "FreshnessAssessment",
    "CompensationPeriod",
    "CompensationRange",
    "CareerSiteSpec",
    "CandidateIdentity",
    "CandidateProfile",
    "CandidateResumeSnapshot",
    "CompiledOntology",
    "CompiledOntologyRelation",
    "CompiledOntologyTerm",
    "CandidateSpan",
    "ClaimAssessment",
    "ClaimKind",
    "ClaimParameters",
    "EvidenceProvenance",
    "EvidenceAtom",
    "EvidenceBundle",
    "EnrichmentTask",
    "EvidencePolarity",
    "ExtractedOntologyClaim",
    "ExtractedRoleSkillEdge",
    "DedupKeyKind",
    "DuplicateRecord",
    "DuplicateRejectionReason",
    "DecisionResult",
    "CompensationExpectation",
    "ExtractionRejectionReason",
    "EmploymentType",
    "FilterProfile",
    "Job",
    "JobDraft",
    "JobExtractionStatus",
    "JobnessDecision",
    "JobGroup",
    "JobLineage",
    "JobRecord",
    "JobReviewReason",
    "JobValidationRejectionReason",
    "JobStatus",
    "LanguageCode",
    "MatchDecision",
    "MaterializedOntologyTerms",
    "OntologySnapshot",
    "OntologyEdge",
    "OntologyEvidence",
    "OntologyNode",
    "OntologyTermStat",
    "ManagedCandidateProfile",
    "PostType",
    "PageKind",
    "OutputSpec",
    "PresentableJob",
    "ProfileCatalog",
    "ProfileMatchScore",
    "ProvenanceTrail",
    "ProfileWeights",
    "QuarantinedRawItem",
    "RawItem",
    "RawItemRejectionReason",
    "RelevanceClassification",
    "RelevanceEvidenceClassification",
    "ResolutionTask",
    "RejectedItem",
    "RejectedOutcome",
    "RelevanceKeyword",
    "RememberedDedupKey",
    "RiskLevel",
    "RuntimeSourceRecord",
    "ScheduleSpec",
    "SearchProfile",
    "Seniority",
    "ShotExtraction",
    "ShotOntologyExtraction",
    "ShotOntologyGraph",
    "SkillTag",
    "StructuredSourceEvidence",
    "SourceAssessmentResult",
    "SourceCapabilities",
    "SourceEvidence",
    "SourceAttribution",
    "SourceHealth",
    "SourceFamily",
    "SourceIdentity",
    "source_identity_for_raw_item",
    "source_identity_for_parts",
    "SourceKind",
    "TenantConfig",
    "TenantInfo",
    "TriageRejectionReason",
    "RelevanceCard",
    "WorkMode",
    "WorkState",
    "aggregate_bundle",
    "aggregate_claim",
    "compute_group_id",
    "compute_content_version",
    "compute_identity_fingerprint",
    "draft_to_record",
    "create_job_group",
    "merge_job_into_group",
    "remove_job_from_group",
    "dedup_company_for_raw_item",
    "dedup_content_key_for_raw_item",
    "dedup_similarity_text_for_raw_item",
    "dedup_text_for_raw_item",
    "dedup_title_for_raw_item",
    "dedup_url_for_raw_item",
    "merge_jobs",
    "processed_key_for_raw_item",
    "ObservationLedgerEntry",
    "ObservationKind",
    "content_hash_for_raw_item",
    "DeliveryEnvelope",
    "OutboxRecord",
    "OutboxState",
    "SourceOutcome",
    "delivery_envelope_from_record",
    "delivery_idempotency_key",
    "processed_key_for_url",
    "job_to_draft",
    "job_to_record",
    "build_job_lineage",
    "source_spec_identifier",
    "source_spec_locator",
    "source_spec_name",
]
